manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/andrewjrae/zmk/tree/keycode-pre-releasing
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
